name: "infra.preview-deploy"

on:
  push:
    branches:
      - main
    paths: .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Hello World"
